import type {
  ActivityItem,
  AdminUser,
  AuditLog,
  Client,
  Coupon,
  DashboardStats,
  Notification,
  Payout,
  Plan,
  PlanDistribution,
  RevenuePoint,
  Subscription,
  Transaction,
} from "../types";

export const currentAdmin: AdminUser = {
  id: "admin-1",
  name: "Zerror Studios",
  email: "hello@zerrorstudios.com",
  role: "Super Admin",
  status: "active",
  lastLogin: "2026-03-28T08:15:00Z",
  avatarInitials: "ZS",
};

export const plans: Plan[] = [
  {
    id: "plan-free",
    name: "Free",
    priceMonthly: 0,
    features: ["Up to 25 products", "1 GB storage", "Basic analytics", "Community support"],
    clientCount: 4,
    limits: { products: 25, storageGb: 1, bandwidthGb: 10 },
  },
  {
    id: "plan-starter",
    name: "Starter",
    priceMonthly: 29,
    features: ["Up to 250 products", "10 GB storage", "Order exports", "Email support"],
    clientCount: 5,
    limits: { products: 250, storageGb: 10, bandwidthGb: 50 },
  },
  {
    id: "plan-pro",
    name: "Pro",
    priceMonthly: 99,
    features: ["Up to 2,000 products", "50 GB storage", "Advanced analytics", "Priority support"],
    clientCount: 4,
    limits: { products: 2000, storageGb: 50, bandwidthGb: 200 },
  },
  {
    id: "plan-enterprise",
    name: "Enterprise",
    priceMonthly: 299,
    features: ["Unlimited products", "500 GB storage", "Custom SLA", "Dedicated CSM"],
    clientCount: 2,
    limits: { products: 10000, storageGb: 500, bandwidthGb: 2000 },
  },
];

export const clients: Client[] = [
  {
    id: "cli-01",
    storeName: "Aura Apparel",
    ownerName: "Maya Chen",
    ownerEmail: "maya@auraapparel.com",
    plan: "Enterprise",
    status: "active",
    mrr: 299,
    orders30d: 1842,
    revenue: 128400,
    growthPercent: 18.4,
    lastActive: "2026-03-28T06:40:00Z",
    joinedDate: "2024-02-12",
    usage: { products: 4200, storageGb: 186, bandwidthGb: 940 },
    notes: "Priority account. Quarterly business review scheduled for April.",
  },
  {
    id: "cli-02",
    storeName: "Nordic Nest Home",
    ownerName: "Erik Johansson",
    ownerEmail: "erik@nordicnest.io",
    plan: "Pro",
    status: "active",
    mrr: 99,
    orders30d: 612,
    revenue: 48200,
    growthPercent: 9.2,
    lastActive: "2026-03-27T21:10:00Z",
    joinedDate: "2024-06-03",
    usage: { products: 880, storageGb: 22, bandwidthGb: 110 },
    notes: "Interested in Enterprise upgrade after Q2 campaign.",
  },
  {
    id: "cli-03",
    storeName: "Byte & Brew",
    ownerName: "Priya Nair",
    ownerEmail: "priya@bytebrew.co",
    plan: "Starter",
    status: "active",
    mrr: 29,
    orders30d: 221,
    revenue: 9800,
    growthPercent: 4.1,
    lastActive: "2026-03-28T02:05:00Z",
    joinedDate: "2025-01-18",
    usage: { products: 140, storageGb: 4.2, bandwidthGb: 28 },
    notes: "",
  },
  {
    id: "cli-04",
    storeName: "Lumen Cosmetics",
    ownerName: "Sofia Alvarez",
    ownerEmail: "sofia@lumencosmetics.com",
    plan: "Pro",
    status: "active",
    mrr: 99,
    orders30d: 905,
    revenue: 71350,
    growthPercent: 22.7,
    lastActive: "2026-03-28T09:00:00Z",
    joinedDate: "2024-09-22",
    usage: { products: 640, storageGb: 31, bandwidthGb: 155 },
    notes: "High AOV brand. Featured in partner case study.",
  },
  {
    id: "cli-05",
    storeName: "TrailForge Gear",
    ownerName: "Jordan Miles",
    ownerEmail: "jordan@trailforge.com",
    plan: "Starter",
    status: "trial",
    mrr: 0,
    orders30d: 48,
    revenue: 2100,
    growthPercent: 0,
    lastActive: "2026-03-26T14:22:00Z",
    joinedDate: "2026-03-10",
    usage: { products: 62, storageGb: 1.8, bandwidthGb: 6 },
    notes: "Trial ends April 10. Send conversion nurture sequence.",
  },
  {
    id: "cli-06",
    storeName: "Canvas & Clay",
    ownerName: "Amelia Brooks",
    ownerEmail: "amelia@canvasclay.studio",
    plan: "Free",
    status: "active",
    mrr: 0,
    orders30d: 34,
    revenue: 890,
    growthPercent: -2.4,
    lastActive: "2026-03-25T11:45:00Z",
    joinedDate: "2025-08-01",
    usage: { products: 18, storageGb: 0.6, bandwidthGb: 3.2 },
    notes: "Hobby seller. Low upgrade likelihood.",
  },
  {
    id: "cli-07",
    storeName: "Volt Mobility",
    ownerName: "Kenji Sato",
    ownerEmail: "kenji@voltmobility.jp",
    plan: "Enterprise",
    status: "active",
    mrr: 299,
    orders30d: 1320,
    revenue: 210500,
    growthPercent: 14.8,
    lastActive: "2026-03-28T07:55:00Z",
    joinedDate: "2023-11-05",
    usage: { products: 5100, storageGb: 320, bandwidthGb: 1450 },
    notes: "Multi-warehouse setup. Dedicated CSM: Anika.",
  },
  {
    id: "cli-08",
    storeName: "Petals & Stem",
    ownerName: "Hannah Lee",
    ownerEmail: "hannah@petalsstem.com",
    plan: "Starter",
    status: "active",
    mrr: 29,
    orders30d: 176,
    revenue: 6400,
    growthPercent: 6.5,
    lastActive: "2026-03-27T18:30:00Z",
    joinedDate: "2025-03-14",
    usage: { products: 95, storageGb: 3.1, bandwidthGb: 19 },
    notes: "",
  },
  {
    id: "cli-09",
    storeName: "Orbit Gadgets",
    ownerName: "Marcus Webb",
    ownerEmail: "marcus@orbitgadgets.com",
    plan: "Pro",
    status: "suspended",
    mrr: 0,
    orders30d: 12,
    revenue: 54000,
    growthPercent: -41.2,
    lastActive: "2026-03-12T09:18:00Z",
    joinedDate: "2024-04-28",
    usage: { products: 1100, storageGb: 40, bandwidthGb: 80 },
    notes: "Suspended for repeated chargebacks. Under review.",
  },
  {
    id: "cli-10",
    storeName: "Harbor Kitchen",
    ownerName: "Olivia Grant",
    ownerEmail: "olivia@harborkitchen.com",
    plan: "Pro",
    status: "active",
    mrr: 99,
    orders30d: 488,
    revenue: 35600,
    growthPercent: 11.3,
    lastActive: "2026-03-28T01:20:00Z",
    joinedDate: "2024-12-02",
    usage: { products: 420, storageGb: 18, bandwidthGb: 92 },
    notes: "",
  },
  {
    id: "cli-11",
    storeName: "Drift Skate Co.",
    ownerName: "Leo Martinez",
    ownerEmail: "leo@driftskate.co",
    plan: "Starter",
    status: "trial",
    mrr: 0,
    orders30d: 27,
    revenue: 1250,
    growthPercent: 0,
    lastActive: "2026-03-24T16:05:00Z",
    joinedDate: "2026-03-15",
    usage: { products: 44, storageGb: 1.1, bandwidthGb: 4.5 },
    notes: "Referred by Aura Apparel partnership.",
  },
  {
    id: "cli-12",
    storeName: "Silk Route Spices",
    ownerName: "Aisha Rahman",
    ownerEmail: "aisha@silkroutespices.com",
    plan: "Starter",
    status: "active",
    mrr: 29,
    orders30d: 303,
    revenue: 15200,
    growthPercent: 15.6,
    lastActive: "2026-03-27T22:40:00Z",
    joinedDate: "2025-05-20",
    usage: { products: 210, storageGb: 6.4, bandwidthGb: 35 },
    notes: "Strong growth in Middle East shipping lanes.",
  },
  {
    id: "cli-13",
    storeName: "Paperplane Press",
    ownerName: "Noah Kim",
    ownerEmail: "noah@paperplanepress.com",
    plan: "Free",
    status: "active",
    mrr: 0,
    orders30d: 19,
    revenue: 420,
    growthPercent: 1.2,
    lastActive: "2026-03-22T10:12:00Z",
    joinedDate: "2025-11-09",
    usage: { products: 12, storageGb: 0.4, bandwidthGb: 1.8 },
    notes: "",
  },
  {
    id: "cli-14",
    storeName: "Alpine Botanics",
    ownerName: "Clara Weiss",
    ownerEmail: "clara@alpinebotanics.ch",
    plan: "Free",
    status: "suspended",
    mrr: 0,
    orders30d: 0,
    revenue: 1800,
    growthPercent: -100,
    lastActive: "2026-02-01T08:00:00Z",
    joinedDate: "2025-07-30",
    usage: { products: 8, storageGb: 0.2, bandwidthGb: 0.5 },
    notes: "Account suspended for ToS violation (prohibited goods).",
  },
  {
    id: "cli-15",
    storeName: "Neon Arcade Merch",
    ownerName: "Tyler Brooks",
    ownerEmail: "tyler@neonarcade.store",
    plan: "Free",
    status: "active",
    mrr: 0,
    orders30d: 91,
    revenue: 3200,
    growthPercent: 27.9,
    lastActive: "2026-03-28T04:50:00Z",
    joinedDate: "2026-01-05",
    usage: { products: 24, storageGb: 0.9, bandwidthGb: 8.1 },
    notes: "Likely Starter upgrade candidate — near Free product limit.",
  },
];

export const subscriptions: Subscription[] = [
  {
    id: "sub-01",
    clientId: "cli-01",
    clientName: "Aura Apparel",
    plan: "Enterprise",
    status: "active",
    renewalDate: "2026-10-12",
    mrr: 299,
    amountDue: 0,
    startedAt: "2025-10-12",
  },
  {
    id: "sub-02",
    clientId: "cli-02",
    clientName: "Nordic Nest Home",
    plan: "Pro",
    status: "active",
    renewalDate: "2026-10-03",
    mrr: 99,
    amountDue: 0,
    startedAt: "2025-10-03",
  },
  {
    id: "sub-03",
    clientId: "cli-03",
    clientName: "Byte & Brew",
    plan: "Starter",
    status: "active",
    renewalDate: "2026-09-30",
    mrr: 29,
    amountDue: 0,
    startedAt: "2025-09-30",
  },
  {
    id: "sub-04",
    clientId: "cli-04",
    clientName: "Lumen Cosmetics",
    plan: "Pro",
    status: "active",
    renewalDate: "2026-09-29",
    mrr: 99,
    amountDue: 99,
    startedAt: "2025-09-29",
  },
  {
    id: "sub-05",
    clientId: "cli-05",
    clientName: "TrailForge Gear",
    plan: "Starter",
    status: "trialing",
    renewalDate: "2026-10-10",
    mrr: 0,
    amountDue: 0,
    startedAt: "2026-09-26",
  },
  {
    id: "sub-06",
    clientId: "cli-07",
    clientName: "Volt Mobility",
    plan: "Enterprise",
    status: "active",
    renewalDate: "2026-10-05",
    mrr: 299,
    amountDue: 0,
    startedAt: "2025-10-05",
  },
  {
    id: "sub-07",
    clientId: "cli-08",
    clientName: "Petals & Stem",
    plan: "Starter",
    status: "pending",
    renewalDate: "2026-09-28",
    mrr: 29,
    amountDue: 29,
    startedAt: "2026-08-28",
  },
  {
    id: "sub-08",
    clientId: "cli-09",
    clientName: "Orbit Gadgets",
    plan: "Pro",
    status: "past_due",
    renewalDate: "2026-09-12",
    mrr: 0,
    amountDue: 99,
    startedAt: "2025-09-12",
  },
  {
    id: "sub-09",
    clientId: "cli-10",
    clientName: "Harbor Kitchen",
    plan: "Pro",
    status: "active",
    renewalDate: "2026-10-02",
    mrr: 99,
    amountDue: 0,
    startedAt: "2025-10-02",
  },
  {
    id: "sub-10",
    clientId: "cli-12",
    clientName: "Silk Route Spices",
    plan: "Starter",
    status: "active",
    renewalDate: "2026-10-20",
    mrr: 29,
    amountDue: 0,
    startedAt: "2026-10-01",
  },
  {
    id: "sub-11",
    clientId: "cli-14",
    clientName: "Alpine Botanics",
    plan: "Starter",
    status: "canceled",
    renewalDate: "2026-09-01",
    mrr: 0,
    amountDue: 0,
    startedAt: "2025-09-01",
    canceledAt: "2026-10-02",
  },
  {
    id: "sub-12",
    clientId: "cli-11",
    clientName: "Drift Skate Co.",
    plan: "Starter",
    status: "trialing",
    renewalDate: "2026-10-08",
    mrr: 0,
    amountDue: 0,
    startedAt: "2026-09-24",
  },
];

export const transactions: Transaction[] = [
  {
    id: "txn-01",
    clientId: "cli-01",
    clientName: "Aura Apparel",
    amount: 299,
    currency: "INR",
    gateway: "Stripe",
    status: "success",
    date: "2026-10-02T10:00:00Z",
    dueDate: "2026-10-01",
    transactionId: "ch_3PqR8a2eZvKYlo2C",
  },
  {
    id: "txn-02",
    clientId: "cli-04",
    clientName: "Lumen Cosmetics",
    amount: 99,
    currency: "INR",
    gateway: "Stripe",
    status: "pending",
    date: "2026-10-01T14:22:00Z",
    dueDate: "2026-09-29",
    transactionId: "ch_3PqT9b2eZvKYlo2D",
  },
  {
    id: "txn-03",
    clientId: "cli-07",
    clientName: "Volt Mobility",
    amount: 299,
    currency: "INR",
    gateway: "Razorpay",
    status: "success",
    date: "2026-10-03T08:40:00Z",
    dueDate: "2026-10-03",
    transactionId: "pay_N8xK2mQpL9aR",
  },
  {
    id: "txn-04",
    clientId: "cli-09",
    clientName: "Orbit Gadgets",
    amount: 99,
    currency: "INR",
    gateway: "Stripe",
    status: "failed",
    date: "2026-10-01T09:05:00Z",
    dueDate: "2026-09-12",
    transactionId: "ch_3PqFail2eZvKY",
  },
  {
    id: "txn-05",
    clientId: "cli-02",
    clientName: "Nordic Nest Home",
    amount: 99,
    currency: "INR",
    gateway: "Stripe",
    status: "success",
    date: "2026-10-01T11:15:00Z",
    dueDate: "2026-10-01",
    transactionId: "ch_3PqU1c2eZvKYlo2E",
  },
  {
    id: "txn-06",
    clientId: "cli-10",
    clientName: "Harbor Kitchen",
    amount: 49.5,
    currency: "INR",
    gateway: "Stripe",
    status: "refunded",
    date: "2026-09-18T16:50:00Z",
    dueDate: "2026-09-15",
    transactionId: "ch_3PqRef2eZvKY",
  },
  {
    id: "txn-07",
    clientId: "cli-12",
    clientName: "Silk Route Spices",
    amount: 29,
    currency: "INR",
    gateway: "Razorpay",
    status: "success",
    date: "2026-10-01T07:30:00Z",
    dueDate: "2026-10-01",
    transactionId: "pay_M3nL8vRtK2bQ",
  },
  {
    id: "txn-08",
    clientId: "cli-03",
    clientName: "Byte & Brew",
    amount: 29,
    currency: "INR",
    gateway: "Stripe",
    status: "success",
    date: "2026-09-18T09:10:00Z",
    dueDate: "2026-09-18",
    transactionId: "ch_3PqV2d2eZvKYlo2F",
  },
  {
    id: "txn-09",
    clientId: "cli-06",
    clientName: "Canvas & Clay",
    amount: 0,
    currency: "INR",
    gateway: "Stripe",
    status: "success",
    date: "2026-10-04T12:00:00Z",
    dueDate: "2026-10-04",
    transactionId: "ch_3PqOct2eZvKY",
  },
];

export const payouts: Payout[] = [
  {
    id: "po-01",
    period: "Feb 2026",
    amount: 18420,
    commission: 2763,
    status: "paid",
    payoutDate: "2026-03-05",
    gateway: "Stripe",
  },
  {
    id: "po-02",
    period: "Jan 2026",
    amount: 16110,
    commission: 2416,
    status: "paid",
    payoutDate: "2026-02-05",
    gateway: "Stripe",
  },
  {
    id: "po-03",
    period: "Mar 2026",
    amount: 19850,
    commission: 2977,
    status: "processing",
    payoutDate: "2026-04-05",
    gateway: "Stripe",
  },
  {
    id: "po-04",
    period: "Dec 2025",
    amount: 14200,
    commission: 2130,
    status: "paid",
    payoutDate: "2026-01-05",
    gateway: "Razorpay",
  },
];

export const coupons: Coupon[] = [
  {
    id: "cpn-01",
    code: "LAUNCH25",
    discountType: "percent",
    discountValue: 25,
    appliesTo: "Starter",
    redemptions: 48,
    maxRedemptions: 100,
    expiresAt: "2026-06-30",
    active: true,
  },
  {
    id: "cpn-02",
    code: "PRO50OFF",
    discountType: "fixed",
    discountValue: 50,
    appliesTo: "Pro",
    redemptions: 12,
    maxRedemptions: 50,
    expiresAt: "2026-04-30",
    active: true,
  },
  {
    id: "cpn-03",
    code: "ENTERPRISE10",
    discountType: "percent",
    discountValue: 10,
    appliesTo: "Enterprise",
    redemptions: 3,
    maxRedemptions: 20,
    expiresAt: "2026-12-31",
    active: true,
  },
  {
    id: "cpn-04",
    code: "WELCOME15",
    discountType: "percent",
    discountValue: 15,
    appliesTo: "All",
    redemptions: 210,
    maxRedemptions: 500,
    expiresAt: "2025-12-31",
    active: false,
  },
];

export const adminUsers: AdminUser[] = [
  currentAdmin,
  {
    id: "admin-2",
    name: "Anika Patel",
    email: "anika@zcommerce.io",
    role: "Support Agent",
    status: "active",
    lastLogin: "2026-03-28T07:40:00Z",
    avatarInitials: "AP",
  },
  {
    id: "admin-3",
    name: "Marcus Reed",
    email: "marcus@zcommerce.io",
    role: "Billing Manager",
    status: "active",
    lastLogin: "2026-03-27T19:05:00Z",
    avatarInitials: "MR",
  },
  {
    id: "admin-4",
    name: "Lena Ortiz",
    email: "lena@zcommerce.io",
    role: "Read-only",
    status: "invited",
    lastLogin: "—",
    avatarInitials: "LO",
  },
  {
    id: "admin-5",
    name: "Sam Okonkwo",
    email: "sam@zcommerce.io",
    role: "Support Agent",
    status: "disabled",
    lastLogin: "2026-02-14T12:00:00Z",
    avatarInitials: "SO",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "log-01",
    adminName: "Zerror Studios",
    action: "Suspended client",
    target: "Orbit Gadgets",
    timestamp: "2026-03-12T10:30:00Z",
    ipAddress: "203.0.113.42",
  },
  {
    id: "log-02",
    adminName: "Anika Patel",
    action: "Updated plan limits",
    target: "Pro plan",
    timestamp: "2026-03-20T15:12:00Z",
    ipAddress: "198.51.100.17",
  },
  {
    id: "log-03",
    adminName: "Marcus Reed",
    action: "Created coupon",
    target: "PRO50OFF",
    timestamp: "2026-03-08T09:45:00Z",
    ipAddress: "203.0.113.88",
  },
  {
    id: "log-04",
    adminName: "Zerror Studios",
    action: "Invited user",
    target: "lena@zcommerce.io",
    timestamp: "2026-03-25T11:20:00Z",
    ipAddress: "203.0.113.42",
  },
  {
    id: "log-05",
    adminName: "Anika Patel",
    action: "Added internal note",
    target: "TrailForge Gear",
    timestamp: "2026-03-26T14:40:00Z",
    ipAddress: "198.51.100.17",
  },
  {
    id: "log-06",
    adminName: "Marcus Reed",
    action: "Refunded transaction",
    target: "ch_3PqRef2eZvKY",
    timestamp: "2026-03-18T17:05:00Z",
    ipAddress: "203.0.113.88",
  },
];

export const activityFeed: ActivityItem[] = [
  {
    id: "act-01",
    type: "signup",
    title: "New signup",
    description: "Drift Skate Co. started a Starter trial",
    timestamp: "2026-03-28T08:10:00Z",
  },
  {
    id: "act-02",
    type: "upgrade",
    title: "Plan upgrade",
    description: "Silk Route Spices upgraded from Free to Starter",
    timestamp: "2026-03-27T16:25:00Z",
  },
  {
    id: "act-03",
    type: "failed_payment",
    title: "Failed payment",
    description: "Orbit Gadgets — Stripe charge declined (?99)",
    timestamp: "2026-03-12T09:05:00Z",
  },
  {
    id: "act-04",
    type: "cancellation",
    title: "Cancellation",
    description: "Alpine Botanics subscription canceled",
    timestamp: "2026-03-01T13:40:00Z",
  },
  {
    id: "act-05",
    type: "upgrade",
    title: "Plan upgrade",
    description: "Lumen Cosmetics moved from Starter to Pro",
    timestamp: "2026-02-28T10:15:00Z",
  },
  {
    id: "act-06",
    type: "signup",
    title: "New signup",
    description: "TrailForge Gear started a Starter trial",
    timestamp: "2026-03-10T12:00:00Z",
  },
  {
    id: "act-07",
    type: "payout",
    title: "Payout processed",
    description: "February platform commission payout completed",
    timestamp: "2026-03-05T06:00:00Z",
  },
  {
    id: "act-08",
    type: "downgrade",
    title: "Plan downgrade",
    description: "Canvas & Clay moved from Starter to Free",
    timestamp: "2026-02-20T09:30:00Z",
  },
];

export const notifications: Notification[] = [
  {
    id: "ntf-01",
    category: "Orders",
    title: "Orders",
    description: "Aura Apparel hit 1,800 orders this month",
    timestamp: "2026-03-28T07:40:00Z",
    dateGroup: "Today",
    read: false,
  },
  {
    id: "ntf-02",
    category: "Billing",
    title: "Billing",
    description: "Failed payment on Orbit Gadgets subscription",
    timestamp: "2026-03-12T09:10:00Z",
    dateGroup: "Earlier",
    read: false,
  },
  {
    id: "ntf-03",
    category: "Analytics",
    title: "Analytics",
    description: "Platform MRR grew 8.2% week over week",
    timestamp: "2026-03-27T18:00:00Z",
    dateGroup: "Yesterday",
    read: true,
  },
  {
    id: "ntf-04",
    category: "Shipping",
    title: "Shipping",
    description: "Volt Mobility reported elevated return rate",
    timestamp: "2026-03-26T11:20:00Z",
    dateGroup: "Earlier",
    read: true,
  },
  {
    id: "ntf-05",
    category: "Orders",
    title: "Orders",
    description: "Lumen Cosmetics placed a bulk wholesale order spike",
    timestamp: "2026-03-28T05:15:00Z",
    dateGroup: "Today",
    read: false,
  },
];

export const revenueTrend: RevenuePoint[] = [
  { month: "Apr", revenue: 42000, mrr: 780 },
  { month: "May", revenue: 45500, mrr: 820 },
  { month: "Jun", revenue: 48100, mrr: 860 },
  { month: "Jul", revenue: 51200, mrr: 910 },
  { month: "Aug", revenue: 54800, mrr: 940 },
  { month: "Sep", revenue: 57200, mrr: 970 },
  { month: "Oct", revenue: 60500, mrr: 1010 },
  { month: "Nov", revenue: 64200, mrr: 1080 },
  { month: "Dec", revenue: 69800, mrr: 1120 },
  { month: "Jan", revenue: 72400, mrr: 1180 },
  { month: "Feb", revenue: 76100, mrr: 1240 },
  { month: "Mar", revenue: 81200, mrr: 1282 },
];

export const planDistribution: PlanDistribution[] = [
  { name: "Free", value: 4, color: "#94A3B8" },
  { name: "Starter", value: 5, color: "#60A5FA" },
  { name: "Pro", value: 4, color: "#2563EB" },
  { name: "Enterprise", value: 2, color: "#1E3A8A" },
];

export const dashboardStats: DashboardStats = {
  totalRevenue: 81200,
  totalRevenueChange: 6.7,
  activeClients: 11,
  activeClientsChange: 4.2,
  mrr: 1282,
  mrrChange: 3.4,
  totalOrders: 6098,
  totalOrdersChange: -1.8,
};
